### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by vladandrei14** [AlexPascu001/proiect-PAO#1]
1. Not related to the project but might be important for future: Add .gitignore file for unwanted/not needed files commited in git (.idea or out directory). If somebody have the **out** directory it can deploy your project without needing to build the code :)
2. Banking, Card, Customer packages could be children of a parent package named model
3. Packages should start with lower case e.e banking, card, customer, service
4. Account: line 107: usually we create custom exceptions for our use case e.g InsufficientFundsException, BalanceException
5. Transaction: use custom Exceptions for iban and amount
6. Card: unused imports
7. Card: IBAN and expiryDate could be final
8. Card:33: name is redundant in constructor
9. Card:52: Creating a new Random object each time a random value is needed is inefficient and may produce numbers which are not random depending on the JDK. For better efficiency and randomness, create a single Random, then store, and reuse it.
10. Card:16 : privat static final (that should be the order)
11. Card:43: You use both Mat.random() and Random class. pick one
12. MasterCard and Visa are children of Card and share the same behaviour. They could easily could be just instances of Card. IF they need to be children of Card they need to have different bahaviour. You can have an abstract fee() method in Card that could be implemented differently for each payment schema.
13. Customer: 19 (nitpicking): second diamond operator is not needed cuz will inherit the one from declaration
14. Customer: 21 and BankService:17 : You never throw Exception; you throw IllegalArgumentException.
15. Customer: use custom exceptions for the issues that could come when constructing a Customer. The exception will be handled in BankService and logged (in the CSV file as part of the auditing system) approprietly based on the Exception type.
16. BankService:20 and 37: when handling exception in catch block we usually dont throw a new one (you could have thrown the Exception in the first place), but we usually log the reason behind the Exception. You will need to do this as part of the project as an auditing system when writing in the CSV file
17. Customer:19 and 26: Correctly updating a static field from a non-static method is tricky to get right and could easily lead to bugs if there are multiple class instances and/or multiple threads in play. Ideally, static fields are only updated from synchronized static methods.
18. Main: unused imports
19. Main (nitpicking) you could use have some private methods for creating and displaying data 
20. Main:37: please use filterTransactions in a different way. maybe create an ArrayList before calling the method and not creting on the spot when calling it. 
21. AuditService: please close io streams to avoid resource leaks

**Comment by AlexPascu001** [comment]
Mersi de feedback, o sa tin cont. Acestea ar fi puncte in minus la evaluarea finala?

Trimis de pe Outlook pentru iOS<https://aka.ms/o0ukef>
________________________________
De la: vladandrei14 ***@***.***>
Trimis: Thursday, April 27, 2023 12:45:38 PM
Către: AlexPascu001/proiect-PAO ***@***.***>
Cc: Subscribed ***@***.***>
Subiect: [AlexPascu001/proiect-PAO] Code review (Issue #1)


  1.  Not related to the project but might be important for future: Add .gitignore file for unwanted/not needed files commited in git (.idea or out directory). If somebody have the out directory it can deploy your project without needing to build the code :)
  2.  Banking, Card, Customer packages could be children of a parent package named model
  3.  Packages should start with lower case e.e banking, card, customer, service
  4.  Account: line 107: usually we create custom exceptions for our use case e.g InsufficientFundsException, BalanceException
  5.  Transaction: use custom Exceptions for iban and amount
  6.  Card: unused imports
  7.  Card: IBAN and expiryDate could be final
  8.  Card:33: name is redundant in constructor
  9.  Card:52: Creating a new Random object each time a random value is needed is inefficient and may produce numbers which are not random depending on the JDK. For better efficiency and randomness, create a single Random, then store, and reuse it.
  10. Card:16 : privat static final (that should be the order)
  11. Card:43: You use both Mat.random() and Random class. pick one
  12. MasterCard and Visa are children of Card and share the same behaviour. They could easily could be just instances of Card. IF they need to be children of Card they need to have different bahaviour. You can have an abstract fee() method in Card that could be implemented differently for each payment schema.
  13. Customer: 19 (nitpicking): second diamond operator is not needed cuz will inherit the one from declaration
  14. Customer: 21 and BankService:17 : You never throw Exception; you throw IllegalArgumentException.
  15. Customer: use custom exceptions for the issues that could come when constructing a Customer. The exception will be handled in BankService and logged (in the CSV file as part of the auditing system) approprietly based on the Exception type.
  16. BankService:20 and 37: when handling exception in catch block we usually dont throw a new one (you could have thrown the Exception in the first place), but we usually log the reason behind the Exception. You will need to do this as part of the project as an auditing system when writing in the CSV file
  17. Customer:19 and 26: Correctly updating a static field from a non-static method is tricky to get right and could easily lead to bugs if there are multiple class instances and/or multiple threads in play. Ideally, static fields are only updated from synchronized static methods.
  18. Main: unused imports
  19. Main (nitpicking) you could use have some private methods for creating and displaying data
  20. Main:37: please use filterTransactions in a different way. maybe create an ArrayList before calling the method and not creting on the spot when calling it.

**Comment by vladandrei14** [comment]
Cu drag!
Eu nu voi depuncta acum, insa o voi face daca problemele reapar in urmatoarea faza a proiectului. (sau daca au fost introduse probleme noi)

**Comment by AlexPascu001** [comment]
Super atunci, mersi.
In cazul acesta, pot sa mai trimit pt feedback inainte de evaluarea finala pentru a putea corecta erorile si din etapa a doua?

**Comment by vladandrei14** [comment]
Din pacate nu. Mi-a luat 2-3 saptamani sa fac review-ul asta 😅

**Comment by AlexPascu001** [comment]
Okay, atunci in principiu ar trebui sa nu am niciun warning? Poate ai timp la un laborator sa faci un “quick review” :)

Trimis de pe Outlook pentru iOS<https://aka.ms/o0ukef>
________________________________
De la: vladandrei14 ***@***.***>
Trimis: Thursday, April 27, 2023 10:53:14 PM
Către: AlexPascu001/proiect-PAO ***@***.***>
Cc: Ionut Alexandru Pascu ***@***.***>; Comment ***@***.***>
Subiect: Re: [AlexPascu001/proiect-PAO] Code review (Issue #1)


Din pacate nu. Mi-a luat 2-3 saptamani sa fac review-ul asta 😅

**Comment by AlexPascu001** [comment]
Salutare!
Am modificat cu recomandarile tale, dar voiam sa te intreb: "unused imports" mi se pare ca e cam ciudat, mai ales cand am de importat 5-6 chestii, nu face antetul fisierului sa fie prea incarcat? Si la Main, aveam doar pachetele de banking, customer si card, pe care le foloseam sa instantiez obiecte.

From: vladandrei14 ***@***.***>
Sent: Thursday, April 27, 2023 12:46 PM
To: AlexPascu001/proiect-PAO ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AlexPascu001/proiect-PAO] Code review (Issue #1)


  1.  Not related to the project but might be important for future: Add .gitignore file for unwanted/not needed files commited in git (.idea or out directory). If somebody have the out directory it can deploy your project without needing to build the code :)
  2.  Banking, Card, Customer packages could be children of a parent package named model
  3.  Packages should start with lower case e.e banking, card, customer, service
  4.  Account: line 107: usually we create custom exceptions for our use case e.g InsufficientFundsException, BalanceException
  5.  Transaction: use custom Exceptions for iban and amount
  6.  Card: unused imports
  7.  Card: IBAN and expiryDate could be final
  8.  Card:33: name is redundant in constructor
  9.  Card:52: Creating a new Random object each time a random value is needed is inefficient and may produce numbers which are not random depending on the JDK. For better efficiency and randomness, create a single Random, then store, and reuse it.
  10. Card:16 : privat static final (that should be the order)
  11. Card:43: You use both Mat.random() and Random class. pick one
  12. MasterCard and Visa are children of Card and share the same behaviour. They could easily could be just instances of Card. IF they need to be children of Card they need to have different bahaviour. You can have an abstract fee() method in Card that could be implemented differently for each payment schema.
  13. Customer: 19 (nitpicking): second diamond operator is not needed cuz will inherit the one from declaration
  14. Customer: 21 and BankService:17 : You never throw Exception; you throw IllegalArgumentException.
  15. Customer: use custom exceptions for the issues that could come when constructing a Customer. The exception will be handled in BankService and logged (in the CSV file as part of the auditing system) approprietly based on the Exception type.
  16. BankService:20 and 37: when handling exception in catch block we usually dont throw a new one (you could have thrown the Exception in the first place), but we usually log the reason behind the Exception. You will need to do this as part of the project as an auditing system when writing in the CSV file
  17. Customer:19 and 26: Correctly updating a static field from a non-static method is tricky to get right and could easily lead to bugs if there are multiple class instances and/or multiple threads in play. Ideally, static fields are only updated from synchronized static methods.
  18. Main: unused imports
  19. Main (nitpicking) you could use have some private methods for creating and displaying data
  20. Main:37: please use filterTransactions in a different way. maybe create an ArrayList before calling the method and not creting on the spot when calling it.

-
